import { GameAsset, Project } from '@/types/gameforge';
import { getSmartCropVariants, getGenerativeVariations, getBackgroundRemovedUrl } from './cloudinary';

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-cyberpunk-rpg',
    name: 'Cyberpunk RPG 2099',
    description: 'Futuristic sci-fi open world RPG with neon environments and cybernetic heroes.',
    gameEngine: 'Unity',
    assetCount: 1248,
    characterCount: 324,
    environmentCount: 187,
    createdAt: '2026-08-10T10:00:00Z'
  },
  {
    id: 'proj-dungeon-crawler',
    name: 'Dungeon Realm 3D',
    description: 'Dark fantasy roguelike with mythic bosses, enchanted items, and ancient ruins.',
    gameEngine: 'Unreal Engine',
    assetCount: 680,
    characterCount: 142,
    environmentCount: 210,
    createdAt: '2026-08-25T14:30:00Z'
  },
  {
    id: 'proj-pixel-platformer',
    name: 'Pixel Knight Adventures',
    description: 'Retro 16-bit action platformer featuring pixel art heroes and boss sprites.',
    gameEngine: 'Godot',
    assetCount: 412,
    characterCount: 95,
    environmentCount: 110,
    createdAt: '2026-09-01T09:15:00Z'
  }
];

// High quality curated Unsplash/Cloudinary fallback URLs representing AI-generated game assets
const SAMPLE_ASSET_IMAGES = {
  cyberWarrior: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=1024&q=80&auto=format&fit=crop',
  dragonLord: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=1024&q=80&auto=format&fit=crop',
  sciFiBlaster: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1024&q=80&auto=format&fit=crop',
  cyberCity: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1024&q=80&auto=format&fit=crop',
  healthPotion: 'https://images.unsplash.com/photo-1514517220017-8ce97a34a7b6?w=1024&q=80&auto=format&fit=crop',
  kungfuPanda: 'https://images.unsplash.com/photo-1564349683136-77e08dba1ef9?w=1024&q=80&auto=format&fit=crop'
};

export const INITIAL_ASSETS: GameAsset[] = [
  {
    id: 'asset-kungfu-panda',
    projectId: 'proj-dungeon-crawler',
    projectName: 'Dungeon Realm 3D',
    cloudinaryPublicId: 'gameforge/kungfu_panda_hero',
    name: 'Master Kung Fu Panda Warrior',
    assetType: 'Character',
    style: '3D Game Art',
    prompt: 'Kung fu panda warrior hero in golden martial arts robes, battle stance, 3d game character render',
    aspectRatio: '1:1',
    thumbnailUrl: SAMPLE_ASSET_IMAGES.kungfuPanda,
    originalUrl: SAMPLE_ASSET_IMAGES.kungfuPanda,
    bgRemovedUrl: getBackgroundRemovedUrl(SAMPLE_ASSET_IMAGES.kungfuPanda),
    tags: ['panda', 'kung-fu', 'warrior', 'character', 'martial-arts', 'hero', '3d-model', 'cloudinary-ai'],
    width: 1024,
    height: 1024,
    format: 'png',
    createdAt: '2026-09-15T10:00:00Z',
    smartCrops: getSmartCropVariants(SAMPLE_ASSET_IMAGES.kungfuPanda),
    variations: getGenerativeVariations(SAMPLE_ASSET_IMAGES.kungfuPanda, 'Kung fu panda warrior hero in golden martial arts robes')
  },
  {
    id: 'asset-cyber-warrior',
    projectId: 'proj-cyberpunk-rpg',
    projectName: 'Cyberpunk RPG 2099',
    cloudinaryPublicId: 'gameforge/cyberpunk_warrior_v1',
    name: 'Cybernetic Exo-Warrior',
    assetType: 'Character',
    style: '3D Game Art',
    prompt: 'Cyberpunk warrior with futuristic glowing cyan armor, plasma sword, high contrast 3d render',
    aspectRatio: '1:1',
    thumbnailUrl: SAMPLE_ASSET_IMAGES.cyberWarrior,
    originalUrl: SAMPLE_ASSET_IMAGES.cyberWarrior,
    bgRemovedUrl: getBackgroundRemovedUrl(SAMPLE_ASSET_IMAGES.cyberWarrior),
    tags: ['cyberpunk', 'warrior', 'armor', 'character', 'sci-fi', 'glowing', 'humanoid', 'cloudinary-ai'],
    width: 1024,
    height: 1024,
    format: 'png',
    createdAt: '2026-09-12T11:20:00Z',
    smartCrops: getSmartCropVariants(SAMPLE_ASSET_IMAGES.cyberWarrior),
    variations: getGenerativeVariations(SAMPLE_ASSET_IMAGES.cyberWarrior, 'Cyberpunk warrior with futuristic glowing cyan armor')
  },
  {
    id: 'asset-dragon-lord',
    projectId: 'proj-dungeon-crawler',
    projectName: 'Dungeon Realm 3D',
    cloudinaryPublicId: 'gameforge/dragon_lord_boss',
    name: 'Infernal Dragon Overseer',
    assetType: 'Character',
    style: '3D Game Art',
    prompt: 'Mythic dark dragon lord with volcanic obsidian scales, molten fire wings, game boss render',
    aspectRatio: '1:1',
    thumbnailUrl: SAMPLE_ASSET_IMAGES.dragonLord,
    originalUrl: SAMPLE_ASSET_IMAGES.dragonLord,
    bgRemovedUrl: getBackgroundRemovedUrl(SAMPLE_ASSET_IMAGES.dragonLord),
    tags: ['dragon', 'boss', 'monster', 'character', 'fantasy', 'fire', 'volcanic', 'cloudinary-ai'],
    width: 1024,
    height: 1024,
    format: 'png',
    createdAt: '2026-09-14T08:45:00Z',
    smartCrops: getSmartCropVariants(SAMPLE_ASSET_IMAGES.dragonLord),
    variations: getGenerativeVariations(SAMPLE_ASSET_IMAGES.dragonLord, 'Mythic dark dragon lord with volcanic obsidian scales')
  },
  {
    id: 'asset-scifi-city',
    projectId: 'proj-cyberpunk-rpg',
    projectName: 'Cyberpunk RPG 2099',
    cloudinaryPublicId: 'gameforge/neon_district_env',
    name: 'Neon Metropolis Alley',
    assetType: 'Environment',
    style: 'Photorealistic',
    prompt: 'Rain-soaked cyberpunk alleyway, towering neon skyscrapers, reflective puddles, dark atmosphere 8k',
    aspectRatio: '16:9',
    thumbnailUrl: SAMPLE_ASSET_IMAGES.cyberCity,
    originalUrl: SAMPLE_ASSET_IMAGES.cyberCity,
    bgRemovedUrl: getBackgroundRemovedUrl(SAMPLE_ASSET_IMAGES.cyberCity),
    tags: ['cyberpunk', 'city', 'environment', 'neon', 'sci-fi', 'rain', 'level-design', 'cloudinary-ai'],
    width: 1920,
    height: 1080,
    format: 'jpg',
    createdAt: '2026-09-13T16:10:00Z',
    smartCrops: getSmartCropVariants(SAMPLE_ASSET_IMAGES.cyberCity),
    variations: getGenerativeVariations(SAMPLE_ASSET_IMAGES.cyberCity, 'Rain-soaked cyberpunk alleyway')
  },
  {
    id: 'asset-scifi-blaster',
    projectId: 'proj-cyberpunk-rpg',
    projectName: 'Cyberpunk RPG 2099',
    cloudinaryPublicId: 'gameforge/plasma_blaster_v3',
    name: 'Hyperion Plasma Rifle',
    assetType: 'Item/Prop',
    style: '3D Game Art',
    prompt: 'Futuristic sci-fi energy blaster gun with glowing blue cartridge, game inventory prop item',
    aspectRatio: '1:1',
    thumbnailUrl: SAMPLE_ASSET_IMAGES.sciFiBlaster,
    originalUrl: SAMPLE_ASSET_IMAGES.sciFiBlaster,
    bgRemovedUrl: getBackgroundRemovedUrl(SAMPLE_ASSET_IMAGES.sciFiBlaster),
    tags: ['weapon', 'item', 'prop', 'plasma', 'rifle', 'inventory', 'sci-fi', 'cloudinary-ai'],
    width: 1024,
    height: 1024,
    format: 'png',
    createdAt: '2026-09-14T19:30:00Z',
    smartCrops: getSmartCropVariants(SAMPLE_ASSET_IMAGES.sciFiBlaster),
    variations: getGenerativeVariations(SAMPLE_ASSET_IMAGES.sciFiBlaster, 'Futuristic sci-fi energy blaster gun')
  },
  {
    id: 'asset-health-potion',
    projectId: 'proj-pixel-platformer',
    projectName: 'Pixel Knight Adventures',
    cloudinaryPublicId: 'gameforge/elixir_vitality',
    name: 'Elixir of Vitality',
    assetType: 'UI/Icon',
    style: 'Pixel Art',
    prompt: 'Glowing red health potion in crystal flask, retro pixel art icon, 16-bit game asset',
    aspectRatio: '1:1',
    thumbnailUrl: SAMPLE_ASSET_IMAGES.healthPotion,
    originalUrl: SAMPLE_ASSET_IMAGES.healthPotion,
    bgRemovedUrl: getBackgroundRemovedUrl(SAMPLE_ASSET_IMAGES.healthPotion),
    tags: ['potion', 'health', 'pixel-art', 'icon', 'ui', 'inventory', '16-bit', 'cloudinary-ai'],
    width: 512,
    height: 512,
    format: 'png',
    createdAt: '2026-09-15T07:12:00Z',
    smartCrops: getSmartCropVariants(SAMPLE_ASSET_IMAGES.healthPotion),
    variations: getGenerativeVariations(SAMPLE_ASSET_IMAGES.healthPotion, 'Glowing red health potion in crystal flask')
  }
];
